# fly.toml app configuration file generated for cade on 2023-06-24T21:50:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cade"
primary_region = "yul"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
